import { z } from "zod";
import type { TenantTheme } from "@/services/tenants/service";

export const THEMES: { id: TenantTheme; color: string }[] = [
  { id: "default", color: "#7c3aed" },
  { id: "slate", color: "#1e293b" },
  { id: "rose", color: "#f43f5e" },
  { id: "emerald", color: "#10b981" },
  { id: "tangerine", color: "#f97316" },
  { id: "ocean", color: "#0ea5e9" },
];

const customThemeSchema = z.object({
  background: z.string().optional(),
  foreground: z.string().optional(),
  card: z.string().optional(),
  cardForeground: z.string().optional(),
  popover: z.string().optional(),
  popoverForeground: z.string().optional(),
  primary: z.string().optional(),
  primaryForeground: z.string().optional(),
  secondary: z.string().optional(),
  secondaryForeground: z.string().optional(),
  muted: z.string().optional(),
  mutedForeground: z.string().optional(),
  accent: z.string().optional(),
  accentForeground: z.string().optional(),
  destructive: z.string().optional(),
  destructiveForeground: z.string().optional(),
  border: z.string().optional(),
  input: z.string().optional(),
  ring: z.string().optional(),
  chart1: z.string().optional(),
  chart2: z.string().optional(),
  chart3: z.string().optional(),
  chart4: z.string().optional(),
  chart5: z.string().optional(),
  sidebar: z.string().optional(),
  sidebarForeground: z.string().optional(),
  sidebarPrimary: z.string().optional(),
  sidebarPrimaryForeground: z.string().optional(),
  sidebarAccent: z.string().optional(),
  sidebarAccentForeground: z.string().optional(),
  sidebarBorder: z.string().optional(),
  sidebarRing: z.string().optional(),
  shadow: z.string().optional(),
  shadowLg: z.string().optional(),
  radius: z.string().optional(),
  backgroundDark: z.string().optional(),
  foregroundDark: z.string().optional(),
  cardDark: z.string().optional(),
  cardForegroundDark: z.string().optional(),
  popoverDark: z.string().optional(),
  popoverForegroundDark: z.string().optional(),
  primaryDark: z.string().optional(),
  primaryForegroundDark: z.string().optional(),
  secondaryDark: z.string().optional(),
  secondaryForegroundDark: z.string().optional(),
  mutedDark: z.string().optional(),
  mutedForegroundDark: z.string().optional(),
  accentDark: z.string().optional(),
  accentForegroundDark: z.string().optional(),
  destructiveDark: z.string().optional(),
  destructiveForegroundDark: z.string().optional(),
  borderDark: z.string().optional(),
  inputDark: z.string().optional(),
  ringDark: z.string().optional(),
  chart1Dark: z.string().optional(),
  chart2Dark: z.string().optional(),
  chart3Dark: z.string().optional(),
  chart4Dark: z.string().optional(),
  chart5Dark: z.string().optional(),
  sidebarDark: z.string().optional(),
  sidebarForegroundDark: z.string().optional(),
  sidebarPrimaryDark: z.string().optional(),
  sidebarPrimaryForegroundDark: z.string().optional(),
  sidebarAccentDark: z.string().optional(),
  sidebarAccentForegroundDark: z.string().optional(),
  sidebarBorderDark: z.string().optional(),
  sidebarRingDark: z.string().optional(),
  shadowDark: z.string().optional(),
  shadowLgDark: z.string().optional(),
  fontHeading: z.string().optional(),
  fontBody: z.string().optional(),
});

export const customizationSchema = z.object({
  theme: z
    .enum(["default", "slate", "rose", "emerald", "tangerine", "ocean"])
    .nullable()
    .optional(),
  mode: z
    .enum(["light", "dark", "auto"])
    .nullable()
    .optional(),
  heroPattern: z.enum(["none", "grid", "dots", "waves"]).nullable().optional(),
  coursesPagePattern: z.enum(["none", "grid", "dots", "waves"]).nullable().optional(),
  showHeaderName: z.boolean().optional(),
  heroTitle: z.string().max(100).optional(),
  heroSubtitle: z.string().max(200).optional(),
  heroCta: z.string().max(50).optional(),
  footerText: z.string().max(200).optional(),
  customTheme: customThemeSchema.nullable().optional(),
});

export type CustomizationFormData = z.infer<typeof customizationSchema>;
