export const ErrorCode = {
  // Auth errors
  TENANT_NOT_SPECIFIED: "TENANT_NOT_SPECIFIED",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  WRONG_TENANT: "WRONG_TENANT",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  INVALID_RESET_TOKEN: "INVALID_RESET_TOKEN",
  INVALID_VERIFICATION_TOKEN: "INVALID_VERIFICATION_TOKEN",
  VERIFICATION_TOKEN_EXPIRED: "VERIFICATION_TOKEN_EXPIRED",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",
  USER_NOT_FOUND: "USER_NOT_FOUND",

  // Authorization errors
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  SUPERADMIN_REQUIRED: "SUPERADMIN_REQUIRED",

  // Tenant errors
  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",
  TENANT_SLUG_EXISTS: "TENANT_SLUG_EXISTS",
  OWNER_ALREADY_HAS_TENANT: "OWNER_ALREADY_HAS_TENANT",

  // Database errors
  UNIQUE_VIOLATION: "UNIQUE_VIOLATION",
  FOREIGN_KEY_VIOLATION: "FOREIGN_KEY_VIOLATION",
  DATABASE_ERROR: "DATABASE_ERROR",

  // Payment errors
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",

  // System errors
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  TIMEOUT: "TIMEOUT",
  CONFLICT: "CONFLICT",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ErrorResponse {
  code: string;
  message: string;
}
